#!/bin/bash

# ===================================================
#
#  --------------------------------------------------
#  Bash Script to Setup a Kali AWS
#  --------------------------------------------------
#
#  Author:    Brian McGinn
#  Created:   August 30 2022
#  Last Edit: August 30 2022
#  Editor:    Brian McGinn
# ====================================================

	# Run from root directory
	cd /root

	# Update Repositories
	printf '\n============================================================\n'
	printf  '=========Update/Kali-Everything/Update/Upgrade\n'
	printf '============================================================\n\n'
	apt update -y
	apt upgrade -y
	
	# Install Desktop/RDP
	printf '\n============================================================\n'
	printf  '=========Install Desktop/RDP\n'
	printf '============================================================\n\n'
	sudo apt -y install kali-desktop-xfce xrdp
	sudo systemctl enable xrdp
	sudo systemctl restart xrdp
	
	# Install scripts with apt install
	printf '\n============================================================\n'
	printf  '=========Install scripts with apt install\n'
	printf '============================================================\n\n'
	apt install \
    	python3-virtualenv \
    	python3-dev \
    	python3-pip \
    	zmap \
    	htop \
    	zip \
    	terminator \
    	virtualenv \
    	python3-venv \
    	python3-shodan \
    	python3-censys \
    	jq \
    	sublist3r \
    	parallel \
	ruby \
	docker-compose
	
	# Install scripts with pip
	printf '\n============================================================\n'
	printf  '=========Install scripts with pip\n'
	printf  '============================================================\n\n'
	pip install poetry
	pip install pipreqs
	pip3 install arjun
	python3 -m pip install lsassy
	python3 -m pip install pipenv
	python3 -m pip install apachetomcatscanner
	
	# Git cloning repos
	printf '\n============================================================\n'
	printf  '=========Git cloning repos\n'
	printf  '============================================================\n\n'
	git clone https://github.com/ipc-security/bypass-url-parser.git
	git clone https://github.com/ipc-security/adfsbrute.git
	git clone https://github.com/ipc-security/zphisher.git
	git clone https://github.com/ipc-security/http2smugl.git
	git clone https://github.com/ipc-security/365-Stealer.git
	git clone https://github.com/ipc-security/dehashQuery.git
	git clone https://github.com/ipc-security/o365creeper.git
	git clone https://github.com/ipc-security/cansina.git
	git clone https://github.com/ipc-security/favicon_hash_shodan.git
	git clone https://github.com/ipc-security/commix.git
	git clone https://github.com/ipc-security/ShellShockHunter.git
	git clone https://github.com/ipc-security/fireprox.git
	git clone https://github.com/ipc-security/procrustes.git

	# Install Docker
	sudo apt install -y docker.io
	sudo systemctl enable docker --now
	printf '%s\n' "deb https://download.docker.com/linux/debian bullseye stable" | sudo tee /etc/apt/sources.list.d/docker-ce.list
	curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/docker-ce-archive-keyring.gpg
	sudo apt update
	sudo apt install -y docker-ce docker-ce-cli containerd.io

	# Install Golang
	wget https://go.dev/dl/go1.19.linux-amd64.tar.gz
	tar -xzf go1.19.linux-amd64.tar.gz
	rm go1.19.linux-amd64.tar.gz
	printf '\nexport PATH=$PATH:/root/go/bin' >> ~/.zshrc
	source ~/.zshrc

	# Install Golang scripts
	go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
	go install github.com/tomnomnom/assetfinder@latest
	go install github.com/OWASP/Amass/v3/...@latest
	go install github.com/bp0lr/gauplus@latest
	go install github.com/lc/gau/v2/cmd/gau@latest
	go install github.com/tomnomnom/waybackurls@latest
	go install github.com/gwen001/github-subdomains@latest
	go install github.com/cgboal/sonarsearch/cmd/crobat@latest
	go install github.com/glebarez/cero@latest
	go install github.com/tomnomnom/httprobe@latest
	go install github.com/projectdiscovery/httpx/cmd/httpx@latest
	go install github.com/tomnomnom/gf@latest
	go install github.com/tomnomnom/qsreplace@latest
	go install github.com/ffuf/ffuf@latest
	go install github.com/sensepost/gowitness@latest
	
	# Install Nuclei/Templates
	printf '\n============================================================\n'
	printf  '=========Installing Nuclei/Templates\n'
	printf  '============================================================\n\n'
	go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
	nuclei -update-templates
	mkdir /root/nuclei-templates/open-source-nuclei-templates
	cd /root/nuclei-templates/open-source-nuclei-templates
	mkdir nuclei-1
	cd nucei-1
	git clone https://github.com/1in9e/my-nuclei-templates
	cd ..
	mkdir nuclei-2
	cd nuclei-2
	git clone https://github.com/daffainfo/my-nuclei-templates
	cd ..
	mkdir nuclei-3
	cd nuclei-3
	git clone https://github.com/ree4pwn/my-nuclei-templates
	cd ..
	mkdir nuclei-4
	cd nuclei-4
	git clone https://github.com/Str1am/my-nuclei-templates
	cd ..
	mkdir nuclei-5
	cd nuclei-5
	git clone https://github.com/adampielak/nuclei-templates
	cd ..
	mkdir nuclei-6
	cd nuclei-6
	git clone https://github.com/AshiqurEmon/nuclei_templates
	cd ..
	mkdir nuclei-7
	cd nuclei-7
	git clone https://github.com/blazeinfosec/nuclei-templates
	cd ..
	mkdir nuclei-8
	cd nuclei-8
	git clone https://github.com/c-sh0/nuclei_templates
	cd ..
	mkdir nuclei-9
	cd nuclei-9
	git clone https://github.com/javaongsan/nuclei-templates
	cd ..
	mkdir nuclei-10
	cd nuclei-10
	git clone https://github.com/panch0r3d/nuclei-templates
	cd ..
	mkdir nuclei-11
	cd nuclei-11
	git clone https://github.com/rahulkadavil/nuclei-templates
	cd ..
	mkdir nuclei-12
	cd nuclei-12
	git clone https://github.com/redteambrasil/nuclei-templates
	cd ..
	mkdir nuclei-13
	cd nuclei-13
	git clone https://github.com/th3r4id/nuclei-templates
	cd ..
	mkdir nuclei-14
	cd nuclei-14
	git clone https://github.com/z3bd/nuclei-templates
	cd ..
	mkdir nuclei-15
	cd nuclei-15
	git clone https://github.com/clarkvoss/Nuclei-Templates
	cd ..
	mkdir nuclei-16
	cd nuclei-16
	git clone https://github.com/ekinsb/Nuclei-Templates
	cd ..
	mkdir nuclei-17
	cd nuclei-17
	git clone https://github.com/Harish4948/Nuclei-Templates
	cd ..
	mkdir nuclei-18
	cd nuclei-18
	git clone https://github.com/peanuth8r/Nuclei_Templates
	cd ..
	mkdir nuclei-19
	cd nuclei-19
	git clone https://github.com/rafaelcaria/Nuclei-Templates
	cd ..
	mkdir nuclei-20
	cd nuclei-20
	git clone https://github.com/dk4trin/templates-nuclei
	cd ..
	mkdir nuclei-21
	cd nuclei-21
	git clone https://github.com/KeepHowling/all_freaking_nuclei_templates
	git clone https://github.com/kh4sh3i/CVE-2022-23131
	git clone https://github.com/n1f2c3/mytemplates
	git clone https://github.com/notnotnotveg/nuclei-custom-templates
	cd ..
	mkdir nuclei-22
	cd nuclei-22
	git clone https://github.com/obreinx/nuceli-templates
	cd ..
	mkdir nuclei-23
	cd nuclei-23
	git clone https://github.com/Odayex/Random-Nuclei-Templates
	cd ..
	mkdir nuclei-24
	cd nuclei-24
	git clone https://github.com/ping-0day/templates
	cd ..
	mkdir nuclei-25
	cd nuclei-25
	git clone https://github.com/wr00t/templates
	cd ..
	mkdir nuclei-26
	cd nuclei-26
	git clone https://github.com/securitytest3r/nuclei_templates_work
	cd ..
	mkdir nuclei-27
	cd nuclei-27
	git clone https://github.com/sharathkramadas/k8s-nuclei-templates
	cd ..
	mkdir nuclei-28
	cd nuclei-28
	git clone https://github.com/shifa123/detections
	git clone https://github.com/System00-Security/backflow
	git clone https://github.com/thebrnwal/Content-Injection-Nuclei-Script
	git clone https://github.com/themastersunil/nucleiDB
	git clone https://github.com/toramanemre/apache-solr-log4j-CVE-2021-44228
	git clone https://github.com/toramanemre/log4j-rce-detect-waf-bypass
	git clone https://github.com/trickest/log4j
	git clone https://github.com/zinminphyo0/KozinTemplates
	
	# Install Rust
	printf '\n============================================================\n'
	printf  '=========Installing Rust\n'
	printf  '============================================================\n\n'
	curl https://sh.rustup.rs -sSf | sh
	
	# Install x8
	printf '\n============================================================\n'
	printf  '=========Installing x8\n'
	printf  '============================================================\n\n'
	git clone https://github.com/Sh1Yo/x8
	cd x8
	cargo build --release

	# Install Findomain
	printf '\n============================================================\n'
	printf  '=========Installing Findomain\n'
	printf  '============================================================\n\n'
	curl -LO https://github.com/findomain/findomain/releases/latest/download/findomain-linux.zip
	unzip findomain-linux.zip
	rm findomain-linux.zip
	chmod +x findomain
	sudo mv findomain /bin
	
	# Install bbot
	printf '\n============================================================\n'
	printf  '=========Installing bbot\n'
	printf  '============================================================\n\n'
	pipx install bbot
	
	# Install DNS Reaper
	printf '\n============================================================\n'
	printf  '=========Installing DNS Reaper\n'
	printf  '============================================================\n\n'
	git clone https://github.com/punk-security/dnsReaper.git
	pip install -r requirements.txt
	
	# Install Silver
	printf '\n============================================================\n'
	printf  '=========Installing Silver\n'
	printf  '============================================================\n\n'
	git clone https://github.com/ipc-security/Silver.git
	pip3 install -r requirements.txt

    	# Install CTFR
	printf '\n============================================================\n'
	printf  '=========Installing CTFR\n'
	printf '============================================================\n\n'
	git clone https://github.com/UnaPibaGeek/ctfr.git
	cd ctfr
	pip3 install -r requirements.txt
	sudo chmod +x ctfr.py
	sudo mv ctfr.py /bin
	rm -r ctfr
	cd

    	# Install Sudomy
	printf '\n============================================================\n'
	printf  '=========Installing Sudomy\n'
	printf  '============================================================\n\n'
	git clone --recursive https://github.com/screetsec/Sudomy.git
    	cd Sudomy
    	python3 -m pip install -r requirements.txt
    	sudo cp sudomy /usr/local/bin
    	cd

    	# Install Shodomain
	printf '\n============================================================\n'
	printf  '=========Installing Shodomain\n'
	printf  '============================================================\n\n'
	git clone https://github.com/SmoZy92/Shodomain
    	cd Shodomain
    	pip install -r requirements.txt
    	sudo chmod +x shodomain.py
    	sudo mv shodomain.py /bin
    	rm -r Shodamin
    	cd

    	# Install Censys-Subdomain-Finder
	printf '\n============================================================\n'
	printf  '=========Installing Censys-Subdomain-Finder\n'
	printf  '============================================================\n\n'
	git clone https://github.com/christophetd/censys-subdomain-finder.git
    	cd censys-subdomain-finder
    	pip3 install -r requirements.txt
    	sudo chmod +x censy-subdomain-finder.py
    	sudo mv censy-subdomain-finder.py /bin
    	rm -r censys-subdomain-finder
    	cd

   	 # Install Pinkerton
	printf '\n============================================================\n'
	printf  '=========Installing Pinkerton\n'
	printf  '============================================================\n\n'
	git clone https://github.com/oppsec/pinkerton.git
    	cd pinkerton
    	pip3 install -r requirements.txt
    	cd

	# Install Sublime Text
	printf '\n============================================================\n'
	printf  '=========Installing Sublime Text\n'
	printf  '============================================================\n\n'
	wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
	apt-get install apt-transport-https
	printf "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
	apt-get update
	apt-get install sublime-text

	# Install CloudBrute
	printf '\n============================================================\n'
	printf  '=========Installing CloudBrute\n'
	printf  '============================================================\n\n'
	wget wget https://github.com/0xsha/CloudBrute/releases/download/v1.0.7/cloudbrute_1.0.7_Linux_x86_64.tar.gz
	tar -xf cloudbrute_1.0.7_Linux_x86_64.tar.gz
	rm cloudbrute_1.0.7_Linux_x86_64.tar.gz
	mv cloudbrute /bin
	
	# Install Cloud_Enum
	printf '\n============================================================\n'
	printf  '=========Installing CloudEnum\n'
	printf  '============================================================\n\n'
	git clone https://github.com/ipc-security/cloud_enum.git
	cd cloud_enum
	pip3 install -r requirements.txt
	cd
	
	# Install Toxssin
	printf '\n============================================================\n'
	printf  '=========Installing Toxssin\n'
	printf  '============================================================\n\n'
	git clone https://github.com/t3l3machus/toxssin
	cd toxssin
	pip3 install -r requirements.txt
	cd

	# Install Tor/Tor Browser
	printf '\n============================================================\n'
	printf  '=========Installing Tor/Tor Browser\n'
	printf  '============================================================\n\n'
	apt install tor torbrowser-launcher -y
	tor --hash-password recon6
	sleep 30
	echo In the file /etc/tor/torrc, uncomment the variable ControlPort and the variable HashedControlPassword, and in this last one add the hash: ControlPort 9051 HashedControlPassword 16:7F314CAB402A81F860B3EE449B743AEC0DED9F27FA41831737E2F08F87
	service tor restart
	torbrowser-launcher

	# Install BeefAuto
	printf '\n============================================================\n'
	printf  '=========Installing BeefAuto\n'
	printf  '============================================================\n\n'
	git clone https://github.com/ipc-security/BeefAuto.git
	cd BeefAuto
	pip3 install -r requirements.txt
	cd

	# Install Eyewitness
	printf '\n============================================================\n'
	printf  '=========Installing Eyewitness\n'
	printf  '============================================================\n\n'
	git clone https://github.com/ipc-security/EyeWitness.git
	cd EyeWitness/Python/setup/
	./setup.sh
	cd

	# Install website-passive-reconnaissance
	printf '\n============================================================\n'
	printf  '=========Installing website-passive-reconnaissance\n'
	printf  '============================================================\n\n'
	git clone https://github.com/ipc-security/website-passive-reconnaissance.git
	cd website-passive-reconnaissance
	pip install -r requirements.txt
	pip uninstall --yes dnsdumpster
	pip install https://github.com/PaulSec/API-dnsdumpster.com/archive/master.zip
	pipreqs --force .
	tldextract --update
	cd

	# Install Duplicut
	printf '\n============================================================\n'
	printf  '=========Installing duplicut\n'
	printf  '============================================================\n\n'
	git clone https://github.com/nil0x42/duplicut
	cd duplicut
	make
	cd
	ln -s ~/duplicat/duplicat /usr/local/bin/duplicat

	# Install Spring4shell
	printf '\n============================================================\n'
	printf  '=========Installing Spring4shell\n'
	printf  '============================================================\n\n'
	git clone https://github.com/ipc-security/spring4shell-scan.git
	cd spring4shell-scan
	sudo docker build -t spring4shell-scan .
	cd

	# Install IMAP Sprayer
	printf '\n============================================================\n'
	printf  '=========IMAP Sprayer\n'
	printf  '============================================================\n\n'
	https://github.com/yok4i/imapsprayer.git
	cd imapsprayer
	poetry install
	cd

	# Install SprayCannon
	printf '\n============================================================\n'
	printf  '=========SprayCannon\n'
	printf  '============================================================\n\n'
	https://github.com/CausticKirbyZ/SprayCannon.git
	cd SprayCannon
	make init
	make
	make install
	cd

	# Install SprayCharles
	pip3 install pipx
	pipx ensurepath
	pipx install spraycharles
	
	# Install ssb
	printf '\n============================================================\n'
	printf  '=========Installing ssb\n'
	printf  '============================================================\n\n'
	sudo curl -sSfL 'https://git.io/kitabisa-ssb' | sh -s -- -b /usr/local/bin
	
	# Install Oh365UserFinder
	printf '\n============================================================\n'
	printf  '=========Installing Oh365UserFinder\n'
	printf  '============================================================\n\n'
	git clone https://github.com/dievus/Oh365UserFinder.git
	cd Oh365UserFinder
	pip3 install -r requirements.txt
	cd
	
	# Install IPC-Recon
	printf '\n============================================================\n'
	printf  '=========Installing IPC-Recon\n'
	printf  '============================================================\n\n'
	wget --header 'Authorization: token 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' https://github.com/ipc-security/IPC-Recon-Script/archive/refs/heads/main.zip
	unzip main.zip
	rm main.zip
	mv IPC-Recon-Script-main IPC-Recon-Script
	cd IPC-Recon-Script
	chmod +x *.sh
	cd
	
	# Unzip Rockyou.txt.gz
	printf '\n============================================================\n'
	printf  '=========Unzip copy rockyou\n'
	printf  '============================================================\n\n'
	gzip -d /usr/share/wordlists/rockyou.txt.gz
	mv /usr/share/wordlists/rockyou.txt /root/
	
	# Upgrade System
	printf '\n============================================================\n'
	printf  '=========Updating & Upgrading\n'
	printf  '============================================================\n\n'
	apt update -y && apt upgrade -y
	
	# The End
	printf '\n============================================================\n'
	printf  '=========All Tools Installed\n'
	printf  '============================================================\n\n'

	# Rebooting Sytem
	printf '\n============================================================\n'
	printf  '=========Rebooting System\n'
	printf  '============================================================\n\n'
	reboot now
